#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImageSearch.Droid.Resource", IsApplication=true)]

namespace ImageSearch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int sections = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int accent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activated_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int divider = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int lightPrimary = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int primary = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int primaryDark = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int primaryText = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int secondaryText = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int textIcon = 2130837512;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int drawer_width = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_edit = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int imageView = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int main_content = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int my_button = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int my_progress = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int my_query = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int recyclerView = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int textView = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int toolbar = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int item_columns = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int item = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int main = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int toolbar = 2131165186;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int menu_gps = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int ApplicationName = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int Hello = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int Navigation = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Search = 2131296259;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int Theme_MyTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int Theme_MyTheme_ActionBar = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int Theme_MyTheme_Base = 2131361794;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
